services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:5000
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - ml
    environment:
      - MONGO_URI=mongodb://mongo:27017/senselearn
      - ML_SERVICE_URL=http://ml:8000
    restart: unless-stopped

  ml:
    build: ./ml
    ports:
      - "8000:8000"
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
    restart: unless-stopped

volumes:
  mongo-data: